name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "*/5 * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz'`
          echo $d > LAST_UPDATED
          echo $d > LAST_UPDATED2
          echo $d > LAST_UPDATED3
          echo $d > LAST_UPDATED4
          echo $d > LAST_UPDATED5
          echo $d > LAST_UPDATED6
          echo $d > LAST_UPDATED7
          echo $d > LAST_UPDATED8
          echo $d > LAST_UPDATED9
          echo $d > LAST_UPDATED10
          
      - name: Commit changes
        run: |
          git config --local user.email "jaytechx@gmail.com"
          git config --local user.name "JayT"
          git add -A
          
          arr[0]="feat: ğŸ˜‚ init commit"
          arr[1]="feat: ğŸ˜± init commit"
          arr[2]="feat: ğŸ‘¿ init commit"
          arr[3]="feat: ğŸ’© init commit"
          arr[4]="feat: ğŸ™ init commit"
          arr[5]="feat: ğŸ™ˆ init commit"
          arr[6]="feat: ğŸ init commit"
          arr[7]="feat: ğŸš€ init commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
